# Generated by Django 4.2.7 on 2023-11-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_id',
        ),
    ]
